### ISSUE TITLE
re: no Microshades hexagon logo

### ISSUE THREAD

**Issue by PythonCoderUnicorn** [KarstensLab/microshades#10]
Hello ! 
I was noticing there is a banner header but no R hexagon logo. Can I design one for this package ? I will adhere strictly to the colours used in the banner. 
 I have made a logo for the Terra package. I will do it for free, need more examples for my portfolio. Please and thank you.

**Comment by lakarstens** [comment]
Hi there! Thank you for the offer (and <3 the terra hex logo!).  Our group has been working on a hex logo (hopefully we will settle on a final one soon :)).

~Lisa
