### ISSUE TITLE
inconsistent bar width

### ISSUE THREAD

**Issue by pchapawsdd** [KarstensLab/microshades#13]
Hello,

Thanks for this cool package! I'm wondering if you have any suggestions on inconsistent section widths within bars in the plots I've been creating. As you can see in the example posted below, the coloured sections in each bar/sample are sometimes different widths to the other sections/colours in the same bar (particularly obvious in the top end of the graph). Any ideas why this might be happening?

![treated_weirdbars](https://user-images.githubusercontent.com/72738927/142082925-0ad18e92-c145-4da4-8720-fd380af71ea3.png)

Here is the plotting code used

```
plot_tads_T_t2 <- plot_microshades(mdf_tads_neworder_T_t2, cdf_tads_neworder_T_t2)
tads_legend_T_t2 <- custom_legend(mdf_tads_neworder_T_t2, cdf_tads_neworder_T_t2, group_level = "Class", subgroup_level = "Genus", legend_key_size = 0.5, legend_text_size = 9)

plot_tads_T1 <- plot_tads_T_t2 + scale_y_continuous(labels = scales::percent, expansion(0)) + theme(legend.position = "none", panel.background = element_blank(), axis.title = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank()) + ggtitle("Treated") + facet_wrap(~ Mother.ID, scales = "free_x", labeller = labeller(Mother.ID = (c("Mother A" = "Sibship A", "Mother B" = "Sibship B", "Mother C" = "Sibship C"))))
plot_tads_T2 <- plot_grid(plot_tads_T1, tads_legend_T_t2)
plot_tads_T2
```

**Comment by erin-d** [comment]
Hi,

Thank you for letting us know about this inconsistent bar width. I am not sure exactly why this occurring, but does this issue go away when figure dimensions are set, or width is increased? 

example `{r fig.width= 12, fig.height=8}`

**Comment by pchapawsdd** [comment]
Thanks for the reply - unfortunately it persists when I set the dimensions/increase width.

**Comment by erin-d** [comment]
What does the plot look like if you run

```
plot_tads_T_t2 <- mdf_tads_neworder_T_t2 %>%
  ggplot(aes_string(x = "Sample", y = "Abundance"), fill = "Phylum Genus") +
  scale_fill_manual(name = "Phylum Genus",
                    values = cdf_tads_neworder_T_t2$hex,
                    breaks = cdf_tads_neworder_T_t2$group) +
  scale_colour_manual(name = "Phylum Genus",
                      values = cdf_tads_neworder_T_t2$hex,
                      breaks = cdf_tads_neworder_T_t2$group) +
  geom_bar(aes(color=group, fill=group), stat="identity", position="stack") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plot_tads_T_t2
```

and then together with the custom legend 
`plot_tads_T2 <- plot_grid(plot_tads_T1, tads_legend_T_t2)
plot_tads_T2`

Do you get the same result?

**Comment by pchapawsdd** [comment]
Yes, unfortunately still the same result.
![micro_test](https://user-images.githubusercontent.com/72738927/144781161-1deddaf4-04bb-4d4d-950f-7b45de7162be.png)

**Comment by erin-d** [comment]
Can you see if this problem persists when you only plot a small subset of your samples? 
Also, if it does persist, would you able to provide a small subset of your data as a .RData file or RDS so I can replicate the problem?

**Comment by pchapawsdd** [comment]
If I plot a subset of 35 samples without a legend, the problem seems to go away. However, adding the legend using plot_grid results in some inconsistencies again (though not as bad as the examples above). 

If I plot the original dataset of around 130 samples without the legend the problem persists as above.

I have emailed you a subset if you'd like to try and replicate - please let me know if this doesn't come through.

**Comment by biocsmith** [comment]
I had this issue with my plots too. I ended up going into the R code for the `plot_microshades` function and copying and editing on the outside. I set `width = 1` and removing the `color = group` from the `geom_bar()` line:

```
group_label = "Phylum Genus"
x = "Sample"
y = "Abundance"
plot <- mdf %>%
    ggplot(aes_string(x = x, y = y), fill = group_label, width = 1) +
    scale_fill_manual(name = group_label,
                      values = cdf$hex,
                      breaks = cdf$group) +
    scale_colour_manual(name = group_label,
                        values = cdf$hex,
                        breaks = cdf$group) +
    geom_bar(aes(fill=group), stat="identity", position="stack") + theme_void() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

plot
```
![pretty_abundance_plot copy](https://user-images.githubusercontent.com/60442486/209401455-e52bf578-fe47-4e13-8131-fa1335b57908.png)



This put a transparent boarder around each bar.

**Comment by lakarstens** [comment]
Thanks for sharing @biocsmith! We were unable to replicate the problem on our end (and therefore unable to troubleshoot it). We will look into updating microshades with your workaround. Are you able to share a data set where you encounter the bar width problem? You can share it by email to karstensLab at gmail.com.

**Comment by awsdd** [comment]
Thanks @biocsmith, this seems to have solved it for me too.

**Comment by KarstensLab** [comment]
Since we have not experienced the issue and do not have a reproducible example, we are going to mark this as closed. If you would like to see the changes in microshades, please send a dataset to KarstensLab(_at_)gmail.com and we will reopen and address the issue.

Thanks!
