### ISSUE TITLE
Custom legend below plot

### ISSUE THREAD

**Issue by MadeleineGundersen** [KarstensLab/microshades#17]
Hi! Thank you for developing this very useful package! 
I was wondering if it is possible to get the custom legend displayed at the bottom of the plot. I tried to play around with the custom_legend function, but couldn't manage to get a working function. Is it a command one could use to choose how to split the rows and columns of the custom_legend? 

Again, thank you for the package! The color combinations and visual display ia so beautiful!

**Comment by lakarstens** [comment]
Glad you like microshades and find it useful! I am not aware of a way to modify the legend, but we will look into it.

**Comment by lakarstens** [comment]
@MadeleineGundersen - @anashen modified the custom legend function to display the legend below the stacked bar plot. We have made a new parameter `legend_orientation`. If you set this to "horizontal" the legend will display along the bottom:

`legend_horiz <- custom_legend(mdf, cdf, legend_orientation="horizontal")`
