### ISSUE TITLE
Relative abundance calculation after tax_glom() gives non-representative relative abundance in figures

### ISSUE THREAD

**Issue by sterrettJD** [KarstensLab/microshades#18]
Hi microshades team,

I've been noticing a bit of a bug in how relative abundances are calculated for microshades.

## Issue description
That is, when using lower levels of taxonomy that might have unclassified taxa, microshades is calculating the relative abundance using only the reads that were classified at that level.   If microshading at the genus level, any taxa that aren't classified at the genus level are thrown out. Because of this, the **relative abundances shown in the figure are not representative of the actual relative abundances.** This also impacts the relative abundances shown for higher taxonomic levels.

## Example
For example, if we had a community with 2 taxa in the family Ruminococcaceae:
 1. Faecalibacterium (50%)
2. Unclassified at the genus level (50%)

Which in phyloseq results in a taxonomy table that has:
 Family				Genus 
 Ruminococcaceae	Faecalibacterium
Ruminococcaceae	\<NA\>

When this is plotted in microshades with subgroup=“Genus”, it throws out the \<NA\> values before calculating relative abundance. In this simple example community, then Feacalibacterium would be plotted as 100% taxa present.

## Further documentation (easy to see the effects in a real data set)
I’ve attached an example knitted Rmarkdown example, where you can click through the different levels, and you can see major changes in relative abundance based on the subgroup level (pdf at the bottom). The knitted Rmd file also has some proposed workarounds. 

## Addressing this?
I think this is happening during speedyseq’s tax_glom function (in prep_mdf). If it is from speedyseq, would it be possible to have an argument that disables this behavior? Or could there be some sort of note in the documentation/examples telling users to handle taxa unclassified at lower taxonomic levels prior to using microshades? 

## Real dataset example
In these figures, particularly reference the "control" microbiomes on the far right. These are contaminated germ free mice, with very low diversity microbiomes, which is why it's so evident. On the family level microshades plot (the first one), it appears that peptostreptococcaceae makes up ~75% of some of the microbiomes. However, the genus level plot shows that they're 90% Turicibacter, which is not in the peptostreptococcaceae family. This is because the main ASV in peptostreptococcaceae was unclassified at the genus level, and it was thrown out for relative abundance calculations, resulting in a misleading relative abundance of Turicibacter presented. You can also see differences in the phylum-level relative abundances of Firmicutes and Bacteroidota in the samples labeled 74. I go into more depth in the knitted Rmd. I've attached it below as a pdf, but it lends itself to better reading (for tabbing through the figures) as html, so I can email that version if you'd like it.

![bad_family_microshades](https://user-images.githubusercontent.com/58188177/229976069-2e5e5efb-3bb9-47c2-bcee-7137d74903c3.png)

![bad_genus_microshades](https://user-images.githubusercontent.com/58188177/229976070-b8fcb089-0621-4b56-9609-a02fa6ac1817.png)

[Taxa-bar.pdf](https://github.com/KarstensLab/microshades/files/11154956/Taxa-bar.pdf)

Thanks again for this package! It's helped our lab make some fantastic plots. I just wanted to bring this behavior to your attention, since it confused me for quite a few days :)

Thanks,
John

**Comment by lakarstens** [comment]
Thank you for pointing this out and the very detailed example! You are correct that the na's are dropped in the tax_glom function. We will work on making this more apparent to users and potentially disabling it. 

In the meantime, the way around this issue is to perform all the functions that occur in prep_mdf independently rather than running the prep_mdf function (i.e. run tax_glom with NArm = FALSE, transform_sample_counts, and ps_melt). 

# Example

    # perform custom mdf_prep
        mdf <- ps %>%

     # agglomerate at specified subgroup level (i.e. Genus)
        speedyseq::tax_glom(subgroup_level, NArm = FALSE) %>%

     # transform sample counts / normalize as desired
        phyloseq::transform_sample_counts(function(x) { x/sum(x) }) %>%

     # melt the phyloseq object
        speedyseq::psmelt()

     # Remove zeros
        mdf_prep <- mdf[mdf$Abundance > 0, ]

**Comment by sterrettJD** [comment]
Thanks for looking into the solution and sending the new `prep_mdf` code!

**Comment by KarstensLab** [comment]
Hi @sterrettJD,
The latest version of microshades now has the option to remove NAs and the default behavior is to NOT remove NAs. See [this vignette](https://karstenslab.github.io/microshades/articles/remove_na_option.html) for more details. 

Thanks again for bringing this to our attention!
~Lisa
