### ISSUE TITLE
[BUG/Version Control] `fct_explicit_na()` was deprecated in forcats 1.0.0.

### ISSUE THREAD

**Issue by erfanshekarriz** [KarstensLab/microshades#19]
Hello!

Just to let you know about a function change in one of your dependencies!

`Warning message:
There was 1 warning in `mutate()`.
ℹ In argument: `Genus = fct_explicit_na(Genus, "Unknown")`.
Caused by warning:
! `fct_explicit_na()` was deprecated in forcats 1.0.0.
ℹ Please use `fct_na_value_to_level()` instead.
ℹ The deprecated feature was likely used in the microshades package.
  Please report the issue to the authors.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. `

Best, 

Erfan

**Comment by lakarstens** [comment]
Thank you for letting us know about this! 
~Lisa

**Comment by lakarstens** [comment]
We have fixed this issue in the pull request by @anashen.
